<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.edderna</groupId>
    <artifactId>springonal</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>springonal-context-annotations-domain</module>
        <module>springonal-context-annotations-application</module>
        <module>springonal-context-annotations-infrastructure</module>
        <module>springonal-context-annotations-interfaces</module>
        <module>springonal-spring-boot-starter</module>
        <module>springonal-core</module>
        <module>springonal-local-env</module>
        <module>springonal-spring-boot-local-env-starter</module>
        <module>springonal-context-annotations</module>
    </modules>

    <properties>
        <maven.compiler.source>22</maven.compiler.source>
        <maven.compiler.target>22</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring.boot.version>3.5.4</spring.boot.version>
        <spring.version>6.2.9</spring.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <version>2.0.0</version>
                <configuration>
                    <licenseName>apache_v2</licenseName>
                    <addSvnKeyWords>false</addSvnKeyWords>
                    <inceptionYear>2025</inceptionYear>
                    <organizationName>Eduardo Daniel Hernandez</organizationName>
                    <projectName>springonal</projectName>
                    <failOnMissingHeader>true</failOnMissingHeader>
                </configuration>
                <executions>
                    <!-- Añadir encabezado -->
                    <execution>
                        <id>add-license-headers</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>update-file-header</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.4.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.4.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.27.4</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>5.18.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>